export enum EMAIL_TYPE {
  REGISTER = 'REGISTER', //注册
  WITHDRAW = 'WITHDRAW', // 提现
  TRANSFER = 'TRANSFER', // 划转
  SECURITY_FORGET = 'SECURITY_FORGET', // 忘记安全码
  PWD_FORGET = 'PWD_FORGET', // 忘记密码
  INVITATION = 'INVITATION', // 邀请
  SECURITY_CHANGE = 'SECURITY_CHANGE', // 修改安全码
  SECURITY_SET = 'SECURITY_SET', // 设置安全码
  SUBORDINATES_CREATE = 'SUBORDINATES_CREATE', // 创建子账户
  TRANSFER_POWER = 'TRANSFER_POWER', // 转让算力
  CHANGE_EMAIL = 'CHANGE_EMAIL', // 修改邮箱
  BIND_EMAIL = 'BIND_EMAIL', // 绑定新邮箱
  RECHARGE = 'RECHARGE', //充值
  AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS', //实名成功
  AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL', //实名失败
  WITHDRAW_NOTICE = 'WITHDRAW_NOTICE', // 提现操作提示
  WITHDRAW_FAILURE = 'WITHDRAW_FAILURE', // 提现失败
  HOT_WALLET_INSUFFICIENT = 'HOT_WALLET_INSUFFICIENT', // 热钱包资金不足
  WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS', // 提现成功
  WITHDRAW_ERROR = 'WITHDRAW_ERROR', // 提现异常
  WITHDRAW_REFUSE = 'WITHDRAW_REFUSE', // 提现拒绝提醒
}
