FROM node:14.17.3-alpine3.14 AS BUILD_IMAGE

WORKDIR /home

COPY . .

RUN npm install --registry=https://registry.npm.taobao.org && \
  npm run prisma:generate && \
  npm run build && \
  npm prune --production

FROM node:14.17.3-alpine3.14

RUN npm install --registry=https://registry.npm.taobao.org && \
  npm install pm2 -g

WORKDIR /home

COPY --from=BUILD_IMAGE /home /home

EXPOSE 7001

ENTRYPOINT ["npm", "run", "docker"]
