/**
* This file is auto-generated by grpc-helper
*/

/* eslint-disable @typescript-eslint/no-namespace */

import * as grpc from '@midwayjs/grpc';

/* package email start */
export namespace email {
  // 服务的定义
  export interface Email {
    // Sends a greeting
    sendEmail(data: SendEmailRequest): Promise<SendEmailReply>;
    getVerificationCode(data: GetVerificationCodeRequest): Promise<GetVerificationCodeReply>;
  }
  /**
   * Email client interface
   */
  export interface EmailClient {
    // Sends a greeting
    sendEmail(options?: grpc.IClientOptions): grpc.IClientUnaryService<SendEmailRequest, SendEmailReply>;
    getVerificationCode(options?: grpc.IClientOptions): grpc.IClientUnaryService<GetVerificationCodeRequest, GetVerificationCodeReply>;
  }
  export interface SendEmailRequest {
    emailType?: string;
    toEmailAddress?: string;
    cacheValue?: string;
    content?: string;
    replaceContent?: email.ReplaceContent;
  }
  export interface ReplaceContent {
    content?: string;
    recommendCode?: string;
  }
  export interface SendEmailReply {
    code?: string;
  }
  export interface GetVerificationCodeRequest {
    emailType?: string;
    cacheValue?: string;
  }
  export interface GetVerificationCodeReply {
    code?: string;
  }
}
/* package email end */
